"""add cascate

Revision ID: 1a59dda5b59b
Revises: a7332cc0a72f
Create Date: 2024-04-20 23:01:04.184144

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1a59dda5b59b"
down_revision: Union[str, None] = "a7332cc0a72f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("addresses_user_id_fkey", "addresses", type_="foreignkey")
    op.create_foreign_key(
        "addresses_user_id_fkey",
        "addresses",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "chapter_contents_course_chapter_id_fkey",
        "chapter_contents",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "chapter_contents_course_chapter_id_fkey",
        "chapter_contents",
        "course_chapters",
        ["course_chapter_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "course_chapters_course_id_fkey", "course_chapters", type_="foreignkey"
    )
    op.create_foreign_key(
        "course_chapters_course_id_fkey",
        "course_chapters",
        "courses",
        ["course_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("courses_course_category_id_fkey", "courses", type_="foreignkey")
    op.drop_constraint("author_courses_fkey", "courses", type_="foreignkey")
    op.create_foreign_key(
        "courses_course_category_id_fkey",
        "courses",
        "course_categories",
        ["course_category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "author_courses_fkey",
        "courses",
        "users",
        ["author_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "favorited_posts_user_id_fkey", "favorited_posts", type_="foreignkey"
    )
    op.drop_constraint(
        "favorited_posts_post_id_fkey", "favorited_posts", type_="foreignkey"
    )
    op.create_foreign_key(
        "favorited_posts_user_id_fkey",
        "favorited_posts",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "favorited_posts_post_id_fkey",
        "favorited_posts",
        "posts",
        ["post_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("posts_user_id_fkey", "posts", type_="foreignkey")
    op.drop_constraint("posts_category_id_fkey", "posts", type_="foreignkey")
    op.create_foreign_key(
        "posts_user_id_fkey",
        "posts",
        "post_categories",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "posts_category_id_fkey",
        "posts",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "user_content_status_chapter_content_id_fkey",
        "user_content_status",
        type_="foreignkey",
    )
    op.drop_constraint(
        "user_content_status_user_id_fkey", "user_content_status", type_="foreignkey"
    )
    op.create_foreign_key(
        "user_content_status_chapter_content_id_fkey",
        "user_content_status",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "user_content_status_user_id_fkey",
        "user_content_status",
        "chapter_contents",
        ["chapter_content_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "user_content_status_user_id_fkey", "user_content_status", type_="foreignkey"
    )
    op.drop_constraint(
        "user_content_status_chapter_content_id_fkey",
        "user_content_status",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "user_content_status_user_id_fkey",
        "user_content_status",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        "user_content_status_chapter_content_id_fkey",
        "user_content_status",
        "chapter_contents",
        ["chapter_content_id"],
        ["id"],
    )
    op.drop_constraint("posts_category_id_fkey", "posts", type_="foreignkey")
    op.drop_constraint("posts_user_id_fkey", "posts", type_="foreignkey")
    op.create_foreign_key(
        "posts_category_id_fkey", "posts", "post_categories", ["category_id"], ["id"]
    )
    op.create_foreign_key("posts_user_id_fkey", "posts", "users", ["user_id"], ["id"])
    op.drop_constraint(
        "favorited_posts_post_id_fkey", "favorited_posts", type_="foreignkey"
    )
    op.drop_constraint(
        "favorited_posts_user_id_fkey", "favorited_posts", type_="foreignkey"
    )
    op.create_foreign_key(
        "favorited_posts_post_id_fkey", "favorited_posts", "posts", ["post_id"], ["id"]
    )
    op.create_foreign_key(
        "favorited_posts_user_id_fkey", "favorited_posts", "users", ["user_id"], ["id"]
    )
    op.drop_constraint("author_courses_fkey", "courses", type_="foreignkey")
    op.drop_constraint("courses_course_category_id_fkey", "courses", type_="foreignkey")
    op.create_foreign_key(
        "author_courses_fkey", "courses", "users", ["author_id"], ["id"]
    )
    op.create_foreign_key(
        "courses_course_category_id_fkey",
        "courses",
        "course_categories",
        ["course_category_id"],
        ["id"],
    )
    op.drop_constraint(
        "course_chapters_course_id_fkey", "course_chapters", type_="foreignkey"
    )
    op.create_foreign_key(
        "course_chapters_course_id_fkey",
        "course_chapters",
        "courses",
        ["course_id"],
        ["id"],
    )
    op.drop_constraint(
        "chapter_contents_course_chapter_id_fkey",
        "chapter_contents",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "chapter_contents_course_chapter_id_fkey",
        "chapter_contents",
        "course_chapters",
        ["course_chapter_id"],
        ["id"],
    )
    op.drop_constraint("addresses_user_id_fkey", "addresses", type_="foreignkey")
    op.create_foreign_key(
        "addresses_user_id_fkey", "addresses", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
