"""Add image_url to courses table

Revision ID: 4b12947b3404
Revises: 46f6e0c41de7
Create Date: 2024-02-12 14:32:25.750207

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b12947b3404"
down_revision: Union[str, None] = "46f6e0c41de7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses", sa.Column("image_url", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###

    op.execute(
        """
        UPDATE courses
        SET image_url = 'dummy';
        """
    )

    op.alter_column("courses", "image_url", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "image_url")
    # ### end Alembic commands ###
