"""create base table

Revision ID: aa7524b7039a
Revises: 0cf73448e24c
Create Date: 2024-04-04 09:02:57.178452

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa7524b7039a"
down_revision: Union[str, None] = "0cf73448e24c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("addresses", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.execute("UPDATE addresses SET created_at = NOW() WHERE created_at IS NULL")
    op.alter_column("addresses", "created_at", nullable=False)

    op.add_column("addresses", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.execute("UPDATE addresses SET updated_at = NOW() WHERE updated_at IS NULL")
    op.alter_column("addresses", "updated_at", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("addresses", "updated_at")
    op.drop_column("addresses", "created_at")
    # ### end Alembic commands ###
