"""post can be unique

Revision ID: aba2aaef5bf2
Revises: 297b8a0f491b
Create Date: 2024-04-07 10:55:12.056972

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aba2aaef5bf2"
down_revision: Union[str, None] = "297b8a0f491b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column("is_unique", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "is_unique")
    # ### end Alembic commands ###
