"""add stripe price id

Revision ID: b2509164e7e6
Revises: 1c7168d6b438
Create Date: 2024-04-25 14:55:58.687788

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2509164e7e6"
down_revision: Union[str, None] = "1c7168d6b438"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("stripe_price_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "stripe_price_id")
    # ### end Alembic commands ###
